version: '3.8'

services:
  mock_webhook:
    build:
      dockerfile: mock_webhook.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WEBHOOK_USERNAME=${WEBHOOK_USERNAME}
      - WEBHOOK_PASSWORD=${WEBHOOK_PASSWORD}
    restart: always
  message_publisher:
    build:
      dockerfile: message_sender.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mock_webhook
      - db
    restart: always
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: insider
      MYSQL_USER: selmant
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql